### ISSUE TITLE
external examples

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/MultiAssayExperiment#102]
@mtmorgan @vjcitn @lwaldron 
Is it okay to load examples from other packages into examples for the MultiAssayExperiment? 
I have used:
```
library(GenomicRanges)
example("GRangesList")
```
to show how to create a `RangedRaggedAssay`.

**Comment by mtmorgan** [comment]
yes, if not already in the DESCRIPTION file, GenomicRanges would go in Suggests:

**Comment by LiNk-NY** [comment]
Thank you! 
GenomicRanges is currently under Imports
