### ISSUE TITLE
names() seems a new requirement

### ISSUE THREAD

**Issue by vjcitn** [vjcitn/MultiAssayExperiment#104]
the API() executive summary seems incorrect as it appears we need names() to succeed for elements of an Elist.  please clarify

**Comment by lwaldron** [comment]
names() should not be a requirement, as per the API.

**Comment by lwaldron** [comment]
I couldn't find any `names()` requirement on Elist elements in the code. To close this issue, create a unit test that:

1. defines a new class, without inheriting it from anything. The new class will just have one slot, containing a RangedSummarizedExperiment.
2. defines the required methods for this new class, as per the API
3. creates a MultiAssayExperiment with an Elist containing this new class.  

This should help catch any requirements existing in the code that aren't documented in the API.

**Comment by lwaldron** [comment]
@vjcitn, note that the package should now protected against this kind of "requirements creep" by the unit test in the changeset [add empty MAE shell class for tests](https://github.com/vjcitn/MultiAssayExperiment/commit/73fed8fa3f7fc055d771e483aee87bb3567d724f).
