### ISSUE TITLE
Updating docs

### ISSUE THREAD

**Issue by PeteHaitch** [vjcitn/MultiAssayExperiment#107]
Running `devtools::document()` on the repo generates different `.Rd` files to what are included in the repo. My guess is that the `.Rd` files have fallen out of sync with the `.R` files in the repo, i.e. `devtools::document()` or the roxygen-equivalent haven't been run. Or perhaps the resulting `.Rd` files haven't been checked into the repo.

**Comment by LiNk-NY** [comment]
This was an issue due to not pushing to upstream as often. Fixed.
