### ISSUE TITLE
methods checking must improve

### ISSUE THREAD

**Issue by vjcitn** [vjcitn/MultiAssayExperiment#109]
I still don't know how to use github
 this code special-cases RSE allowing a second signature element to be "missing" or "ANY"; all other
 types must have only one signature element.  I don't think this is sound.  We can discuss.   
  hasMethod seems to be the right methods infrastructure to use but the set of signatures to be 
  checked should not be so confined. 

```
# Check class conforms to API
.hasMethods <- function(object, my_fun) {
  obj_cl <- class(object)
  if (any(my_fun %in% c("[", "assay"))) {
    if (inherits(object, "RangedSummarizedExperiment")) {
      return(hasMethod(my_fun, signature = c(class(object), "missing")))
    } else {
      return(hasMethod(my_fun, signature = c(obj_cl, "ANY")))
    }
  }
  return(hasMethod(my_fun, signature = obj_cl))
}
```

**Comment by lwaldron** [comment]
You're right Vince - I guess what we really care about is, is there an assay() method for the class, regardless of whether the method has additional elements of the signature?  I expect there's something wrong with this, but all the first arguments of signatures that have an assay class are:

`sapply(findMethods("assay")@signatures, function(x) x[1])`

If the class is found in the vapply() version of this vector, it could pass the check. 

By the way, `assay(rse, i)` returns the ith assay of the (Ranged)SummarizedExperiment, but for such a SE it would be unclear how to respond to the `assay()` query in a MultiAssayExperiment and it would be difficult to pass along the "i" part of the signature to this element only of the MultiAssayExperiment. I think this would be like the discussion we had about the rownames() / colnames() / dimnames() methods, where we agreed (and is not reflected in the API) that "typical", but not required, behavior would be to return a character vector. Having assay(obj) return something other than a numeric matrix would, for example, probably break your correlation-calculating method.

this level of detail is beyond hasMethod() checking.  As long as the SummarizedExperiment has only one assay, then assay() can be called without the second argument of the signature.

**Comment by vjcitn** [comment]
Thanks Levi.  I wonder if we are doing too much checking before the MAE is
constructed.  Methods have to deal with problems, but we want to be able to
construct the containers fairly liberally IMHO.

**Comment by mtmorgan** [comment]
Herve's advice was to do minimal checking, partly because it's hard to do more and partly because it's unclear when / if the things being checked will be a constraint.


________________________________

**Comment by lwaldron** [comment]
I had thought of `assay()` as part of minimal checking because I wouldn't know how to get the matrix of data from Elist elements otherwise. But in favor of removing it as a requirement:

1. it wouldn't be missed for current functionality (which is really just row/column subsetting and keeping sample IDs matched between assays and pData), and 
2. it would "solve" the current problem that this package defines assay() methods for matrix and ExpressionSet, which goes against the principle of leaving base classes pristine. However, we'll need a unified matrix-extractor to be able to create any data analysis methods, and I feel loath to invent new wrapper classes for matrix and ExpressionSet too.

**Comment by lwaldron** [comment]
Proposal:

1. Remove the validity check for `assay()` method from [.getMethErr().](https://github.com/vjcitn/MultiAssayExperiment/blob/master/R/Elist-class.R#L109)
2. Export a function `hasAssay()` that checks that all Elist elements of a MultiAssayExperiment object have an `assay()` method.  Avoid any if/thens in this check, just check the first element of the assay method signatures, as above.
3. Document `hasAssay()` in a new section in the API titled "optional validity checks for developers".  These optional checks could a "soft" version that uses `hasMethod()`, and "hard" option that actually applies the function and checks that a return contract is met.
