### ISSUE TITLE
Elist element colnames validity check should be per assay

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/MultiAssayExperiment#110]
Current check is that all Elist element colnames, when concatenated, should be found in the sampleMap "assay" column.  This check is intended to ensure constant mappability of each column in each assay to a single row of the pData DataFrame, which is not assured by this check.  I have updated the API to reflect the more specific per-assay check that is needed to ensure a consistent MultiAssayExperiment:

1(iii): For each Elist element (say for an element named "assay X"), the sorted colnames of that element must be identical to the sorted "assay" column of the sampleMap, within the rows where the value in the "assayname" column matches the name of that Elist element (in this example, "assay X").

**Comment by LiNk-NY** [comment]
resolved in bc66e6b
