### ISSUE TITLE
Don't export `subset()`

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/MultiAssayExperiment#112]
I don't think there's any need to export `subset()` for MultiAssayExperiment now that `[` is fully functional? As @vjcitn pointed out, `subset(MAE, gr, "rownames")` is confusing terminology when subsetting by a GRanges.

**Comment by LiNk-NY** [comment]
In the case that you are subsetting by a `GRanges` object, you can forgo the `type = "rownames"` argument since it will be handled in subset.

**Comment by lwaldron** [comment]
Fine with me to keep subset around.  Since we now support subsetting by methods other than rownames, I suggest changing the method options to "rows" and "columns".
