### ISSUE TITLE
Keep mcols data in RangedRaggedAssay

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/MultiAssayExperiment#117]
@lwaldron @mtmorgan @vjcitn 
The `mcols(grl)` data for any GRangesList object will be kept in the metadata slot of the RangedRaggedAssay. It can be accessed by `metadata(myRRA)$mcols`. 
Any comments or suggestions?

**Comment by lwaldron** [comment]
Why doesn't `RangedRaggedAssay()` constructor start with the original / complete GRangesList, so that that `mcols(grl)` would still be accessible by `mcols(myRRA)`?

**Comment by LiNk-NY** [comment]
A `GRangesList` that has data in the mcols, after the unlist/relist manipulation, loses the data for some reason. 
I just realized that I can just add that back into the mcols using the replacement method. 
```
mcols(myRRA) <- mcols(grl)
```
Thanks!
