### ISSUE TITLE
Add completeCases method for MultiAssayExperiment

### ISSUE THREAD

**Issue by aedin** [vjcitn/MultiAssayExperiment#131]
Can we have a method which quickly subsets the columns to the intersect across studies. Can this be a default option. 

subsetByColumns(myMAE)

which would return the subset of columns that are in Reduce(intersect(colnames(myMAE))

Thanks
A

**Comment by lwaldron** [comment]
Perhaps a hasCompleteData() function that returns the pData identifiers that have data for every assay would make this easier to do.  @LiNk-NY what is currently the easiest way to subset to only cases having complete data in every assay?

**Comment by aedin** [comment]
HI
I think I prefer complete.cases() rather than hasCompleteData() if we 
can, as it would be familiar to users however is complete.cases() 
written in S4 or S3? Need to check.

**Comment by LiNk-NY** [comment]
The easiest way to subset to only cases having data in every assay is to run TCGAbarcode on all of the sample identifiers (so to get patient IDs) and doing what Aedin mentioned `Reduce(intersect(listOfIdentifiers))` and pass this to the bracket method for subsetting by a character vector of patient identifiers.

**Comment by lwaldron** [comment]
Marcel, correct me if I'm wrong, but that wouldn't work because you would
get a vectors of assay IDs and not primary IDs, unless they happened to be
the same.

**Comment by LiNk-NY** [comment]
This solution is specific to TCGA data. It would take the assay IDs and remove the "sample" portion from the IDs to get primary IDs.  By running reduce and intersect on the list of primary IDs, you'd get a vector of primary IDs which could then be used to subset the MultiAssayExperiment by those participants.

**Comment by LiNk-NY** [comment]
I imagine that `completeCases` would just return a logical vector (where length is nrow(pData)) that indicates biological units with complete cases across all the experiments.

**Comment by lwaldron** [comment]
Agreed.

**Comment by LiNk-NY** [comment]
Generic from S4Vectors used, see 538b79dab7fc1a3ce644e28195f298afc614abd5
