### ISSUE TITLE
Rename Elist class and accessor

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/MultiAssayExperiment#133]
There's an Elist name collision with EList thus proposed renaming: 
- [x] Elist class to `ExperimentList`
- [x] Elist accessor to `experiments`
- [x] Elist replacement method to `experiments<-`

**Comment by LiNk-NY** [comment]
@mtmorgan 
Should the replacement method be based on the accessor function (i.e., "experiments<-")?

**Comment by mtmorgan** [comment]
yep ExperimentList, experiments, experiments<-

**Comment by LiNk-NY** [comment]
Thanks!
