### ISSUE TITLE
Clean up `show` method

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/MultiAssayExperiment#134]
- [x] remove quotes around object class/types
- [x] don't mention slots (use instead `To access:`)
- [x] standardize rows and columns output (0, 0 or 0 x 0)

**Comment by LiNk-NY** [comment]
I opted for `experimentname: 0 x 0 classname`. Any thoughts?

**Comment by mtmorgan** [comment]
exrpimentname: classname with x rows and y columns ? that's pretty short, sort of consistent with GRanges, doesn't leave  the meaning of 0 x 0 up to the imagination.
