### ISSUE TITLE
.git folder too big

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/MultiAssayExperiment#146]
```
du -h MultiAssayExperiment
```
It's about 85 Mb in total usage. About 83 Mb are from the `.git` folder.

**Comment by LiNk-NY** [comment]
Reopened #44

**Comment by lwaldron** [comment]
I just now did a git pull that brought down almost as much:

$ du -hs .git
 77M	.git

**Comment by lwaldron** [comment]
Duplicate of #44.

**Comment by LiNk-NY** [comment]
@lwaldron What repo did you pull from? 
I applied the tool and it was reduced to <4Mb. I have worked on it since.
