### ISSUE TITLE
Travis-CI Erroring

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/MultiAssayExperiment#147]
Recent changes to the repo have make Travis-CI not work. I'm not sure what's wrong. I'm using `%\VignetteEngine{knitr::rmarkdown}` and `knitr` under `Suggests:` and `VignetteBuilder`. This was working fine *previously* until the repo was expanded and contracted. See the error message below:

```
Error: processing vignette 'MultiAssayExperiment.Rmd' failed with diagnostics:

It seems you should call rmarkdown::render() instead of knitr::knit2html() because MultiAssayExperiment.Rmd appears to be an R Markdown v2 document.

Execution halted
```
Link to the build: 
https://travis-ci.org/LiNk-NY/MultiAssayExperiment/builds/144272628

Any thoughts? 

@jimhester your input would be appreciated

Marcel

**Comment by vjcitn** [comment]
On Tue, Jul 12, 2016 at 10:24 PM, Marcel Ramos <notifications@github.com>
wrote:

> Recent changes to the repo have make Travis-CI not work. I'm not sure
> what's wrong. I'm using %\VignetteEngine{knitr::rmarkdown} and knitr
> under Suggests: and
>

knitr::rmarkdown doesn't exist

maybe just try the advice in the warning?

**Comment by LiNk-NY** [comment]
Thanks Vince. 
I spoke to @jimhester about this at useR! 2016 and what I understood was that `knitr` would work with Travis-CI. I made that change in a92cf10d34744a747dda64fcef207de80997ee78 and it was working well until recently.

**Comment by LiNk-NY** [comment]
Seems like I just needed to add `rmarkdown` to the Suggests field.

**Comment by LiNk-NY** [comment]
That solve the issue, see b15ba91e704b028a719a84b3f055114f85503f6c.
