### ISSUE TITLE
re-ordering of columns

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/MultiAssayExperiment#150]
Subsetting by columns does no re-ordering of the columns, for example, here c("Jill", "Jack") produces the same result as c("Jack", "Jill"):

```
> example("MultiAssayExperiment")
> (x=sampleMap(myMultiAssayExperiment[, c("Jill", "Jack"), ]))
DataFrame with 8 rows and 3 columns
       assay     primary     colname
    <factor> <character> <character>
1       Affy        Jack      array1
2       Affy        Jill      array2
3 Methyl450k        Jack     methyl1
4 Methyl450k        Jack     methyl2
5 Methyl450k        Jill     methyl3
6  CNVgistic        Jack   snparray1
7  CNVgistic        Jill   snparray2
8  CNVgistic        Jill   snparray3
```

I am not sure of what the behavior should be here, but I guess I expected the result to look more like this:

```
> x[c(2, 1, 5, 3, 4, 7, 8, 6), ]
DataFrame with 8 rows and 3 columns
       assay     primary     colname
    <factor> <character> <character>
1       Affy        Jill      array2
2       Affy        Jack      array1
3 Methyl450k        Jill     methyl3
4 Methyl450k        Jack     methyl1
5 Methyl450k        Jack     methyl2
6  CNVgistic        Jill   snparray2
7  CNVgistic        Jill   snparray3
8  CNVgistic        Jack   snparray1
> 
```

I don't know of a good solution for doing such re-ordering other than a hack creating a factor of the "primary" column and specifying the levels in the order wanted, and using that for the re-ordering, if the values are non-unique within each assay.  If there are no replicates, then a simple `match()` could be used. Thoughts? @seandavi @mtmorgan @LiNk-NY @kasperdanielhansen @vjcitn @PeteHaitch

**Comment by PeteHaitch** [comment]
The second version matches my expectations. Unsure as to implementation, however.

**Comment by LiNk-NY** [comment]
It might be some costly operation like: 
```
primaries <- c("Jack", "Jack", "Jill")
gg <- unlist(sapply(c("Jill", "Jack"), function (x) which(!is.na(match(primaries, x)))))
primaries[gg]
```
