### ISSUE TITLE
show method for RangedRaggedAssay()

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/MultiAssayExperiment#159]
Not working when running just `RangedRaggedAssay()`

**Comment by mtmorgan** [comment]
bug in GenomicRanges

> > isDisjoint(GRangesList())
> Error in !ans : invalid argument type

**Comment by mtmorgan** [comment]
closed with https://github.com/Bioconductor-mirror/IRanges/commit/579d1a1a3e628998240ef6052d54a9c67173fec6
