### ISSUE TITLE
rename extract() method

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/MultiAssayExperiment#160]
This came up in today's call. Ideas:
- extractToTidy
- asTidyDataFrame

@mtmorgan - what do you think?

**Comment by chapmandu2** [comment]
I would suggest ‘gather’ as this is consistent with tidyr gather vs spread concepts to go to/from long/wide formats.  This was what I settled on in my nascent tidyMultiAssay package - https://github.com/chapmandu2/tidyMultiAssay/tree/master/R

**Comment by seandavi** [comment]
I kinda like it.
