### ISSUE TITLE
RangedRaggedAssay assay() method returns only NAs for partial overlaps

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/MultiAssayExperiment#168]
See example below, there seems to be now way to get a useful result when specifying ranges, I can only get a matrix of NAs. I thought that specifying "type" would be passed on to findOverlaps(), but perhaps this needs to be an explicit argument?  Also FYI @lavkan.

```
> gr1 <-
+ GRanges(seqnames = "chr3", ranges = IRanges(1000, 2000),
+ strand = "+", GC = 0.45, score = 5L)
> gr2 <-
+ GRanges(seqnames = "chr3", ranges = IRanges(1500, 2500),
+ strand = "+", GC = 0.46, score = 6L)
> grl <- GRangesList("gr1" = gr1, "gr2" = gr2)
> myRRA = RangedRaggedAssay(grl)
> myRRA
RangedRaggedAssay with 2 disjoint ranges, 2 samples, and 2 data elements

GC
                  gr1  gr2
chr3:1000-2000:+ 0.45   NA
chr3:1500-2500:+   NA 0.46

score
                 gr1 gr2
chr3:1000-2000:+   5  NA
chr3:1500-2500:+  NA   6

> djr <- disjoin(unlist(grl))
> assay(myRRA, ranges=djr)
                 gr1 gr2
chr3:1000-1499:+  NA  NA
chr3:1500-2000:+  NA  NA
chr3:2001-2500:+  NA  NA
> assay(myRRA, ranges=djr, type="any")
                 gr1 gr2
chr3:1000-1499:+  NA  NA
chr3:1500-2000:+  NA  NA
chr3:2001-2500:+  NA  NA
> 
```

**Comment by lwaldron** [comment]
By the way, the result I am looking for here (whether by specifying type="any" or otherwise, but probably by default) would be:

```
> assay(myRRA, ranges=djr, type="any")
                 gr1 gr2
chr3:1000-1499:+  5  NA
chr3:1500-2000:+  5   6
chr3:2001-2500:+  NA  6

```

**Comment by LiNk-NY** [comment]
The current implementation uses a more strict approach `IRanges::overlapsAny` with `type = "equal"`.

**Comment by lwaldron** [comment]
I see. I think equal ranges will be the exception when specifying the ranges argument. This is one use case, another would be ranges corresponding to genes or exons, which would mostly be within copy number segments.
