### ISSUE TITLE
Strip large binaries from history with BFG

### ISSUE THREAD

**Issue by jimhester** [vjcitn/MultiAssayExperiment#44]
Because large data files were previously included in the git history cloning this repository takes an inordinate amount of time.

However because git allows you to rewrite history you can remove these large files from your history, which will make cloning much quicker in the future.

While you can do this manually using `git-filter-branch` the [BFG Repo Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) is a tool developed to make this process simple and safe to perform.

```bash
git clone --mirror git@github.com:jimhester/biocMultiAssay.git
java -jar bfg.jar --strip-blobs-bigger-than 1M biocMultiAssay.git
cd biocMultiAssay.git
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```
Doing the above takes the repository to 2.2Mb from 552Mb on my machine, so it is a _substantial_ savings.

It should be noted that bfg will not remove a file that exists in the current `HEAD`, so running it with even low values (like 1M) is safe.

You can then `git push --force` this modified repository back to github, and cloning will be very snappy in the future.

**Comment by seandavi** [comment]
Good idea.  Currently, cloning is slow enough to dissuade potential contributors from getting started.

**Comment by vjcitn** [comment]
OK, so I am just going to do this.  Thanks for the tip.

**Comment by vjcitn** [comment]
any concerns about this 'deny updating...'?

%vjcair> git push --force

Counting objects: 618, done.

Delta compression using up to 4 threads.

Compressing objects: 100% (263/263), done.

Writing objects: 100% (618/618), 2.04 MiB | 524.00 KiB/s, done.

Total 618 (delta 314), reused 618 (delta 314)

To git@github.com:vjcitn/biocMultiAssay.git

 + 68af230...2e9c864 master -> master (forced update)

 ! [remote rejected] refs/pull/1/head -> refs/pull/1/head (deny updating a
hidden ref)

 ! [remote rejected] refs/pull/1/merge -> refs/pull/1/merge (deny updating
a hidden ref)

 ! [remote rejected] refs/pull/10/head -> refs/pull/10/head (deny updating
a hidden ref)

**Comment by lwaldron** [comment]
On Fri, Sep 25, 2015 at 10:20 AM, Vince Carey <notifications@github.com>
wrote:

> any concerns about this 'deny updating...'?
>

Only that the push doesn't seem to have gone through...  This guy
<http://robinlovelace.net/r/2014/06/25/pruning-a-giant-gh-repo.html> seems
to think that message is not an issue.


-- 
Levi Waldron
Assistant Professor of Biostatistics
City University of New York School of Public Health, Hunter College
2180 3rd Ave Rm 538
New York NY 10035-4003
phone: 212-396-7747
www.waldronlab.org

**Comment by jimhester** [comment]
I think it is fine,  there is an issue athttps://github.com/rtyley/bfg-repo-cleaner/issues/36 that explains the cause of the massage

**Comment by lwaldron** [comment]
And, it worked!  Of course there is no new push, but the total repo size is
now under 4MB.

**Comment by lwaldron** [comment]
Sorry, it got expanded again, I'm working on it.

**Comment by lwaldron** [comment]
There seems to be a caveat that any forks need to be similarly pruned, or
else a pull request will re-expand the repo.  The main one is now small
again.

**Comment by LiNk-NY** [comment]
It looks like it got expanded again after merging a pull request. Working on it.

**Comment by LiNk-NY** [comment]
I've fixed it but only for my branch. The push isn't working to upstream (vjcitn). 
I'm also getting a failing build on Travis-CI although the package builds fine without it.

**Comment by lwaldron** [comment]
Did you use ```git push --force```? Your collaborator access should be enough to fix the vjcitn main fork, since that's also all I have. I just tried doing it myself but am getting a java exception locally.

**Comment by LiNk-NY** [comment]
`git push --force` worked. Thanks.
