### ISSUE TITLE
yriMulti vignette now uses biocMultiAssay infrastructure

### ISSUE THREAD

**Issue by vjcitn** [vjcitn/MultiAssayExperiment#59]
combines methylation (450k) expr (RNAseq) and dnaseI hypersensitivty assays on YRI samples
with very little fuss.  includes a prototype .subsetByRanges function that uses S4
in a very rudimentary way ... something like an updateObject or callNextMethod might
be relevant

still to come: support lightweight binding/manipulation of ScanVcfParam to support extraction of genotype data from 1000 genomes vcf

**Comment by lwaldron** [comment]
Vince - I'm going to close some issues here that aren't actively seeking resolution; feel free to open again if you want action on the MultiAssayExperiment package.
