### ISSUE TITLE
CharacterList: find targets

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/MultiAssayExperiment#85]
@lwaldron @mtmorgan @vjcitn 
The usual `rownames` contract used to return a list of character vectors via `rownames(myMultiAssay)`. Recent changes to the representation of `rownames` for `RangedRaggedAssay` objects have made it more complicated to subset this list by character. 
```
$`CNV gistic`
CharacterList of length 3
[["snparray1"]] 1=chr3:58000000-59502360:+
[["snparray2"]] 1=chr3:58493000-58501999:+ 2=chr3:3-9002:-
[["snparray3"]] 1=chr1:1-3:- 2=chr2:4-9:-
```
Although I like the output of the CharacterList class, the searching through elements to find a hit would involve something like 
`CharacterList(lapply(rownames(myMultiAssay)[[4]], function(x) {names(x)[names(x) %in% "1"]} ))`
as a `getHits` method for signature `c("RangedRaggedAssay", "character")`. 

Is there another way to approach this? 

Thanks, 
MR

**Comment by mtmorgan** [comment]
Not sure that I understand, but

```
xx = CharacterList(setNames(letters, LETTERS), setNames(LETTERS, letters))
```

And then

```
> relist(names(unlist(xx, use.names=FALSE)) %in% "C", xx)
LogicalList of length 2
[[1]] FALSE FALSE TRUE FALSE FALSE FALSE ... FALSE FALSE FALSE FALSE FALSE
[[2]] FALSE FALSE FALSE FALSE FALSE FALSE ... FALSE FALSE FALSE FALSE FALSE
```
and

```
> xx[relist(names(unlist(xx)) %in% "C", xx)]
CharacterList of length 2
[[1]] C=c
[[2]] named character(0)
```

This is searching for names; for elements is easier, e.g., `xx %in% "C"`, `xx[xx %in% "C"]`, `any(xx %in% "C")`

**Comment by LiNk-NY** [comment]
The rownames representation of a `RangedRaggedAssay` class now only returns a character vector of all the range names in that `RangedRaggedAssay`. This allows for easier subsetting without the need to list and relist as in the previous representation of a `RangedRaggedAssay` that involved the `CharacterList`. 
See: 
```
example("RangedRaggedAssay")
rownames(myRRA)
```
