### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/MultiAssayExperiment#89]
Rename repo to MultiAssayExperiment, then create a new vjcitn/biocMultiAssay just with a README.md that points to the new repo.  This way will keep all the history, issues, wiki, etc.

**Comment by lwaldron** [comment]
Repo, filenames, and code changed to MultiAssayExperiment.  @LiNk-NY there are a couple new documentation warnings.

**Comment by LiNk-NY** [comment]
I am getting an error for `library(GenomicRanges)`

**Comment by lwaldron** [comment]
I'm confused, is that related to this issue?

**Comment by LiNk-NY** [comment]
Well, when running `devtools::document()` I was getting that error and it was holding me up from changing names. This only happened for the development version of Bioconductor. 
Somehow the error went away. It was also visible in other packages but after running `BiocInstaller::biocLite()` it was fixed. 

Thanks, 
MR
